# file: docker_compose/tasks/main.yml
# This is the primary task for the docker_compose role. It installs the
# docker compose via pip, cleaning up any older conflicting version of
# the Python docker libary. This task can be skipped by setting the
# skip_docker_compose variable to true.
---

- name: Clean up docker build
  pip:
    state: absent
    name: "{{item}}"
  loop:
    - docker-py
    - docker-compose
  become: yes
  become_user: root
  become_method: sudo
  when: not skip_docker_compose
  ignore_errors: True
  tags:
    - docker
    - compose


- name: Install docker-compose
  shell: curl -L https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  become: yes
  tags:
    - docker
    - compose

- name: Install docker-compose bash completion
  shell: curl -skL -o /etc/bash_completion.d/docker-compose https://raw.githubusercontent.com/docker/compose/{{docker_compose_version}}/contrib/completion/bash/docker-compose
  become: yes
  tags:
    - docker
    - compose
    - completion

# Aliases, completion, helpers for docker and docker compose
- name: Install docker aliases into user's .bashrc.d directory
  shell: curl -skL -o /etc/profile.d/docker.aliases https://gist.githubusercontent.com/deardooley/011ce72d1e2ad3c03045879f0ea41b25/raw/25ff4601c6ec851c3048cfd02e7b9ced80ecbaeb/docker.aliases.sh
  become: yes
  tags:
    - docker
    - aliases


- name: Add execute permission to completion, alias, and compose files
  file:
    path: "{{item}}"
    mode: 01755
  become: yes
  loop:
    - /etc/profile.d/docker.aliases
    - /etc/bash_completion.d/docker-compose
    - /usr/local/bin/docker-compose
  tags:
    - docker
    - compose
    - completion
    - aliases