# file common/tasks/clean_host.yml
# Cleans up host removing service users, temp data, etc
---
# delete user account and all data. Data on othe volumes and outside of the
# user home directory must be cleaned up separately
- name: remove "{{ agave_linux_user_name }}" user account and data
  user:
    name: "{{ agave_linux_user_name }}"
    remove: True
  become: yes
  become_user: root
  become_method: sudo
  ignore_errors: True
  tags:
    - user
    - login

- name: remove ansible temp dir
  file:
    path: /root/.ansible/tmp
    state: absent
  become: yes
  become_user: root
  become_method: sudo
  ignore_errors: True
  tags:
    - ansible


- name: remove containers
  shell: docker rm -f `docker ps -aq`
  become: yes
  become_user: root
  become_method: sudo
  ignore_errors: True
  tags:
    - docker
