---
#
# Install all "standard" software that could be needed for installing
# other software, and for effectively managing a cluster.  Basically
# this includes the following categories of utilities:
#
# - compression utilities and archivers
# - version control systems
# - a few other misc utilities that one can reasonably expect
#

- name: Clean up broken dpkg locks
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /var/lib/dpkg/lock
    - /var/cache/apt/archives/lock
    - /var/lib/apt/lists/lock
  become: yes
  become_user: root
  become_method: sudo

- name: Clean up broken dpkg locks
  shell: "dpkg --configure -a"
  become: yes
  become_user: root
  become_method: sudo
  ignore_errors: True

- name: Install commonly needed software (Debian-family)
  package:
    name={{item}}
    state=present
    update_cache=yes
  with_items:
    # compression and archivers
    - bzip2
    - gzip
    - tar
    - unzip
    - zip
    # version control systems
    - git
    # other "standard" utilities
    - openssl
    - rsync
    - screen
    - tmux
    - vim
    - jq
    - iftop
  become: yes
  become_user: root
  become_method: sudo
  ignore_errors: True
