# file agave_host/tasks/users.yml
# Tasks for creating service users, configuring sudo and restricting
# login attempts to ssh keys only
---
- name: Add agave group for restricted permissions on shared folders
  group:
    name: agave
    state: present
  become: yes
  become_user: root
  become_method: sudo
  tags:
    - user

- name: Add docker group for access to the docker socket
  group:
    name: docker
    state: present
  become: yes
  become_user: root
  become_method: sudo
  tags:
    - user

- name: Add agave system user service account
  user:
    name: "{{ agave_linux_user_name }}"
    shell: /bin/bash
    groups:
      - agave
      - docker
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096
    state: present
  become: yes
  become_user: root
  become_method: sudo
  tags:
    - user

- name: Add vagrant user to sudoers with no password
  lineinfile:
    dest: /etc/sudoers.d/99-vagrant-user
    line: 'vagrant ALL=(ALL) NOPASSWD:ALL'
    state: present
    create: yes
  become: yes
  become_user: root
  become_method: sudo
  when: ansible_ssh_user == "vagrant"
  tags:
    - user

- name: Add sytem user to sudoers with no password
  lineinfile:
    dest: "/etc/sudoers.d/99-{{ agave_linux_user_name }}-user"
    line: '{{ agave_linux_user_name }} ALL=(ALL) NOPASSWD:ALL'
    state: present
    create: yes
  become: yes
  become_user: root
  become_method: sudo
  tags:
    - user

- name: Add system user's key to authorized keys
  shell: cat id_rsa.pub > authorized_keys chdir="/home/{{ agave_linux_user_name }}/.ssh" creates="/home/{{ agave_linux_user_name }}/.ssh/authorized_keys"
  become: yes
  become_user: "{{ agave_linux_user_name }}"
  become_method: sudo
  tags:
    - user

- name: Ensure permissions on "{{ agave_linux_user_name }}" sudoers
  file: path="/etc/sudoers.d/99-{{ agave_linux_user_name }}-user" mode=0440 owner=root
  become: yes
  become_user: root
  become_method: sudo
  tags:
    - user

- name: give other users access to {{ agave_linux_user_name }} home directory
  file: path="/home/{{ agave_linux_user_name }}" mode=0755
  become: yes
  become_user: root
  become_method: sudo
  tags:
    - user
