# file: docker_aliases/tasks/main.yml
# This is the primary task for the docker_aliases role. It delegates
# installation of docker_aliases, docker_completion, and docker_compose
# completion to the correpsonding task files. Any of these tasks can be
# skipped by setting the respective skip_docker_* variable to true.
---

- name: Install docker_aliases from bitbucket snippets
  get_url:
    url: https://bitbucket.org/!api/2.0/snippets/deardooley/9KL4X/23705c6a46c77c0cf0ec9bddfc6767b51682ae9d/files/docker.aliases
    dest: /etc/profile.d/docker_aliases.sh
    mode: 0755
    force: yes
  become: yes
  become_user: root
  become_method: sudo
  when: not skip_docker_aliases
  tags:
    - completion
    - docker

- name: Install docker bash completion
  get_url:
    url: https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker > /usr/local/etc/bash_completion.d/docker
    dest: /etc/bash_completion.d/docker
    mode: 0755
    force: yes
  become: yes
  become_user: root
  become_method: sudo
  when: not skip_docker_completion
  tags:
    - completion
    - docker

- name: Install docker compose bash completion
  get_url:
    url: https://raw.githubusercontent.com/docker/compose/master/contrib/completion/bash/docker-compose
    dest: /etc/bash_completion.d/docker-compose
    mode: 0755
    force: yes
  become: yes
  become_user: root
  become_method: sudo
  when: not skip_docker_compose_completion
  tags:
    - completion
    - docker
